# Generated by Django 6.0.4 on 2026-04-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_enrollment_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'inscripcion', 'verbose_name_plural': 'inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name': 'progreso de leccion', 'verbose_name_plural': 'progresos de lecciones'},
        ),
    ]
