# Generated by Django 6.0.4 on 2026-04-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'id'], 'verbose_name': 'leccion', 'verbose_name_plural': 'lecciones'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order', 'id'], 'verbose_name': 'seccion', 'verbose_name_plural': 'secciones'},
        ),
    ]
