# Generated by Django 6.0.4 on 2026-05-10 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_category_course_duration_hours_course_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/%Y/%m/%d/', verbose_name='Archivo de video')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nombre original')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='courses.lesson', verbose_name='Lección')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField(verbose_name='Texto completo')),
                ('segments', models.JSONField(blank=True, default=list, help_text='Lista de segmentos con timestamps [{start, end, text}]', verbose_name='Segmentos con timestamps')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Idioma detectado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='courses.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Transcripción',
                'verbose_name_plural': 'Transcripciones',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Resumen')),
                ('key_points', models.JSONField(blank=True, default=list, help_text='Lista de los puntos más importantes', verbose_name='Puntos clave')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='courses.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Resumen',
                'verbose_name_plural': 'Resúmenes',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('options', models.JSONField(help_text='Lista de 4 opciones de respuesta', verbose_name='Opciones')),
                ('correct_option', models.IntegerField(help_text='Índice de la opción correcta (0-3)', verbose_name='Opción correcta')),
                ('explanation', models.TextField(blank=True, help_text='Explicación de por qué la respuesta es correcta', verbose_name='Explicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='courses.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Pregunta de Quiz',
                'verbose_name_plural': 'Preguntas de Quiz',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado')),
                ('current_step', models.CharField(choices=[('waiting', 'En espera'), ('extracting_audio', 'Extrayendo audio'), ('transcribing', 'Transcribiendo'), ('generating_summary', 'Generando resumen'), ('generating_quiz', 'Generando preguntas'), ('done', 'Finalizado')], default='waiting', max_length=30, verbose_name='Paso actual')),
                ('progress_percent', models.IntegerField(default=0, verbose_name='Progreso (%)')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='ID de tarea Celery')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio del procesamiento')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin del procesamiento')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_status', to='courses.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Estado de Procesamiento',
                'verbose_name_plural': 'Estados de Procesamiento',
            },
        ),
    ]
