# Generated by Django 6.0.4 on 2026-04-22 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_tools', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codefeedbacklog',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_feedback_logs', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='codefeedbacklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_feedback_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='exercise_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ai_tools.exerciseset'),
        ),
        migrations.AddField(
            model_name='transcriptionjob',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='courses.lesson'),
        ),
    ]
