# Generated by Django 6.0.4 on 2026-04-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotlog',
            options={'verbose_name': 'registro de chatbot', 'verbose_name_plural': 'registros de chatbot'},
        ),
        migrations.AlterModelOptions(
            name='codefeedbacklog',
            options={'verbose_name': 'feedback de codigo', 'verbose_name_plural': 'feedbacks de codigo'},
        ),
        migrations.AlterModelOptions(
            name='exercisequestion',
            options={'verbose_name': 'pregunta de ejercicio', 'verbose_name_plural': 'preguntas de ejercicios'},
        ),
        migrations.AlterModelOptions(
            name='exerciseset',
            options={'verbose_name': 'set de ejercicios', 'verbose_name_plural': 'sets de ejercicios'},
        ),
        migrations.AlterModelOptions(
            name='transcriptionjob',
            options={'verbose_name': 'transcripcion', 'verbose_name_plural': 'transcripciones'},
        ),
    ]
