# Generated by Django 6.0.4 on 2026-04-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xptransaction',
            options={'verbose_name': 'transaccion de XP', 'verbose_name_plural': 'transacciones de XP'},
        ),
    ]
