# Generated by Django 6.0.4 on 2026-04-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Breve biografía del usuario.'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Preferencias de aprendizaje o configuraciones.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ROLE_FREE', 'Free'), ('ROLE_PREMIUM', 'Premium'), ('ROLE_INSTRUCTOR', 'Instructor'), ('ROLE_ADMIN', 'Admin')], default='ROLE_FREE', max_length=20),
        ),
    ]
