# Generated by Django 6.0.4 on 2026-04-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificate_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'certificado', 'verbose_name_plural': 'certificados'},
        ),
    ]
